project_id = "ozpqwidaeqjffrzqghwj"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54325

[studio]
port = 54323

[inbucket]
port = 54324

[auth]
enabled = true

site_url = "http://localhost:3000"
additional_redirect_urls = []
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.email]
enable_confirmations = true
max_frequency = "1m0s"

[realtime]
enabled = true

[storage]
enabled = true

[edge_functions]
[functions.together]
verify_jwt = true
