// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozpqwidaeqjffrzqghwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96cHF3aWRhZXFqZmZyenFnaHdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNTg5NDUsImV4cCI6MjA2MDkzNDk0NX0.UCUVUN_MVOe5CP0sFLLPh8ZWhSd7q3-9tt84MbzCGqE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);